### ISSUE TITLE
Asset and Art Naming conventions stylesheet

### ISSUE THREAD

**Issue by ben0child** [heygamerspigsquadgroup/Cult-Clash#22]
Create a stylesheet for asset naming conventions.

**Comment by ben0child** [comment]
google doc with updated naming conventions, will be adding stylesheet as we make it.

https://docs.google.com/document/d/1pKZ5Pc6Hcj3n15JnHgH-8GAVV2K9GnnSEe0QFeYp3VA/edit?usp=sharing

**Comment by halemaster** [comment]
Should we put this in the Wiki here? You can just edit the wiki here like any other wiki on the web.
